# Generated by Django 2.2.17 on 2021-04-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicalarea',
            name='image',
            field=models.ImageField(upload_to='geographical_area/'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='image',
            field=models.ImageField(upload_to='organs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
