# Generated by Django 2.2.17 on 2021-03-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeographicalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('affected_organ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Organ')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_frequency', models.PositiveSmallIntegerField(choices=[(0, 'not chosen'), (1, 'very rarely'), (2, 'rarely'), (3, 'sometimes'), (4, 'often'), (5, 'constantly')], default=0)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Symptom')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='affected_organs',
            field=models.ManyToManyField(to='main_app.Organ'),
        ),
        migrations.AddField(
            model_name='disease',
            name='geographical_area',
            field=models.ManyToManyField(to='main_app.GeographicalArea'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(through='main_app.DiseaseSymptom', to='main_app.Symptom'),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment',
            field=models.ManyToManyField(to='main_app.Treatment'),
        ),
    ]
