# Generated by Django 2.2.17 on 2021-02-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
