# Generated by Django 2.2.17 on 2021-02-09 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_organ_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='affected_organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Organ'),
        ),
    ]
